
export type HospitalZone = 'Western' | 'Eastern' | 'Central' | 'Northern';

export interface Hospital {
  name: string;
  address: string;
  zone: HospitalZone;
}

export const HOSPITALS: Hospital[] = [
  // Western Zonal Register
  { name: "NIMASA SAR Base Clinic — NIMASA SARBC EZ PHC", address: "Apapa, Lagos", zone: "Western" },
  { name: "Abbey Medical Centre", address: "14, Idewu Street, Olodi Apapa, Lagos", zone: "Western" },
  { name: "Adeiza Medical Centre", address: "15, Payne Crescent, Apapa, Lagos", zone: "Western" },
  { name: "Asheco Hospital", address: "41, Cardoso Street, Kirikiri, Lagos", zone: "Western" },
  { name: "Bestcare Hospital Limited", address: "2A Keffi Street, Ikoyi, Lagos", zone: "Western" },
  { name: "Christ Medical Centre Ltd.", address: "28, Randle Road, Apapa, Lagos", zone: "Western" },
  { name: "Faramed Clinics", address: "37, Akinwunmi Street, Ijoku Road, Sango Otta, Ogun State", zone: "Western" },
  { name: "Grayma Medical Centre", address: "Apapa Oshodi Express Way, Olodi Apapa, Lagos", zone: "Western" },
  { name: "Heda Hospital", address: "Ajao Estate, Lagos", zone: "Western" },
  { name: "Iduna Specialist Hospital", address: "1, Takoradi Road, Apapa GRA, Lagos", zone: "Western" },
  { name: "Ikeja Medical Centre", address: "11, Ogunmodede Street, Off Allen Avenue, Lagos", zone: "Western" },
  { name: "Imperial Medical Centre", address: "65, Brickfield Road, Ebute Metta, Lagos", zone: "Western" },
  { name: "Ituah Hospital", address: "512 Road, FESTAC Town, Lagos", zone: "Western" },
  { name: "Lifelink Clinic", address: "Off Bode Thomas Road, Surulere, Lagos", zone: "Western" },
  { name: "Majeroh Medical Centre and Dental Services", address: "9, Pelewura Way, Apapa, Lagos", zone: "Western" },
  { name: "Medbury Medical Services", address: "7b, Admiralty Road, Lekki Phase 1, Lagos", zone: "Western" },
  { name: "Motayo Hospital", address: "3, Owoduni Street, Ikeja, Lagos", zone: "Western" },
  { name: "Q-Impact Medicare", address: "Opebi, Lagos", zone: "Western" },
  { name: "St Clement Specialist Hospital", address: "321 Road, C Close, FESTAC Town, Lagos", zone: "Western" },
  { name: "ST. Louis Medical Centre Limited", address: "1, Ado Avenue, Apapa, Lagos", zone: "Western" },
  { name: "T & S Hospital", address: "7, Western Avenue, Ojuelegba, Lagos", zone: "Western" },
  { name: "The Health Arena", address: "128, Stanchan Street, Igboshere, Lagos", zone: "Western" },
  { name: "Tin-Can Hospital Group", address: "47, Calcutta Crescent, Apapa, Lagos", zone: "Western" },
  { name: "Triumph Medical Centre", address: "32, Unity Road, Ikeja, Lagos", zone: "Western" },
  { name: "Watershed Hospital", address: "Okeafa, Lagos", zone: "Western" },
  
  // Eastern Zonal Register
  { name: "AB Health Consortium Ltd", address: "7B, Nzimiro Street, Amadi Flats, Port Harcourt", zone: "Eastern" },
  { name: "Abasiekeme Specialist Hospital", address: "11, Nana Street, Eket, Akwa Ibom", zone: "Eastern" },
  { name: "Acron Medical Consultants", address: "1, Acron Avenue, Port Harcourt", zone: "Eastern" },
  { name: "Adi Specialist Clinic", address: "7A, Otob Abasi Street, Calabar", zone: "Eastern" },
  { name: "Ashford & Patrice Clinic", address: "3, Manila Pepple Street, Port Harcourt", zone: "Eastern" },
  { name: "Bakor Medical Centre", address: "124, MM Highway, Calabar", zone: "Eastern" },
  { name: "Bosom Hospital", address: "Rumuola, Port Harcourt", zone: "Eastern" },
  { name: "Caprin Hospital Ltd.", address: "No. 5, Rumuagholu Road, Port Harcourt", zone: "Eastern" },
  { name: "Castle Clinic Ltd", address: "Shell Location Road, Port Harcourt", zone: "Eastern" },
  { name: "CIMS Medical Services", address: "Transamadi Gardens Estate, Port Harcourt", zone: "Eastern" },
  { name: "Cumi Medical Centre", address: "Woji Town, Port Harcourt", zone: "Eastern" },
  { name: "Datta Medical Centre", address: "21, Awoji Road, Port Harcourt", zone: "Eastern" },
  { name: "Ebony Hospitals Ltd.", address: "9, Orazi Road, Port Harcourt", zone: "Eastern" },
  { name: "Eddy Medical Centre", address: "4, Ndoki Lane, Port Harcourt", zone: "Eastern" },
  { name: "Estee Medical Centre", address: "No. 11, Chief Wodi Street, Port Harcourt", zone: "Eastern" },
  { name: "Goldie Clinic", address: "4, Ekong Nyong Close, Calabar", zone: "Eastern" },
  { name: "Harley Clinic", address: "21B, Akaninwor Road, Port Harcourt", zone: "Eastern" },
  { name: "Harryland Medical Centre", address: "Borikiri, Port Harcourt", zone: "Eastern" },
  { name: "Hilton Clinics", address: "Mile 4, Port Harcourt", zone: "Eastern" },
  { name: "Immanuel Infirmary", address: "Ikot Effanga Mkpa, Calabar", zone: "Eastern" },
  { name: "International SOS Clinic", address: "Amadi Creek, Port Harcourt", zone: "Eastern" },
  { name: "Kez Clinics", address: "Rumuomasi, Port Harcourt", zone: "Eastern" },
  { name: "Krisany Medical Services", address: "D/Line, Port Harcourt", zone: "Eastern" },
  { name: "Maritime Academy Of Nigeria Medical Centre", address: "Oron Campus, Akwa Ibom", zone: "Eastern" },
  { name: "Mercyland Specialist Hospital", address: "East/West Road, Port Harcourt", zone: "Eastern" },
  { name: "Meridian Hospital", address: "21, Igbokwe Street, Port Harcourt", zone: "Eastern" },
  { name: "Morning Star Hospital", address: "19/21, Isiokpo Street, Port Harcourt", zone: "Eastern" },
  { name: "New Mile One Hospital", address: "15, Emenike Street, Port Harcourt", zone: "Eastern" },
  { name: "New Orlins Clinic Ltd", address: "3, Etim Okpoyo Close, Port Harcourt", zone: "Eastern" },
  { name: "NPA Medical Centre", address: "Rivers Ports Complex, Port Harcourt", zone: "Eastern" },
  { name: "NOBSAMS Hospital Ltd", address: "44, Trans Amadi Road, Port Harcourt", zone: "Eastern" },
  { name: "Olunwa Medical Centre", address: "Amadi-Ama Road, Port Harcourt", zone: "Eastern" },
  { name: "Medical Centre Onne", address: "Harbour Road, Onne, Port Harcourt", zone: "Eastern" },
  { name: "Palmers Hospital Limited", address: "5/7, Agip Road, Port Harcourt", zone: "Eastern" },
  { name: "Ponyx Hospitals Ltd", address: "GRA Phase III, Port Harcourt", zone: "Eastern" },
  { name: "Precious Life Medical Centre", address: "4B, Okorodo Street, Port Harcourt", zone: "Eastern" },
  { name: "Princess Medical Centre", address: "Trans-Amadi Ind. Layout, Port Harcourt", zone: "Eastern" },
  { name: "Providence Clinic & Maternity", address: "Railway Close, Port Harcourt", zone: "Eastern" },
  { name: "Rivon Clinic", address: "Rumuogba Residential Area, Port Harcourt", zone: "Eastern" },
  { name: "Save a Life Mission Hospital", address: "38, Uyo Street, Port Harcourt", zone: "Eastern" },
  { name: "Sonabel Hospital Ltd", address: "14, Owbie Road, Port Harcourt", zone: "Eastern" },
  { name: "Sophike Medical Centre", address: "Federal Housing Estate, Port Harcourt", zone: "Eastern" },
  { name: "Springs Hospital", address: "458, Ikwerre Road, Port Harcourt", zone: "Eastern" },
  { name: "St. Martins Hospital", address: "68, Stadium Road, Port Harcourt", zone: "Eastern" },
  { name: "St. Catherine's Specialist Hospitals Ltd.", address: "Trans-Woji Road, Port Harcourt", zone: "Eastern" },
  { name: "St. Patrick's Hospital", address: "3, Eastern By Pass, Port Harcourt", zone: "Eastern" },
  { name: "Stevenson Medicare Limited", address: "Iwowari Avenue, Port Harcourt", zone: "Eastern" },
  { name: "Teme Hospital Limited", address: "New Hospital Close, Port Harcourt", zone: "Eastern" },
  { name: "The Riverside Clinic Limited", address: "21, Harbour Road, Port Harcourt", zone: "Eastern" },
  { name: "The Shield Specialists Hospital Ltd.", address: "Trans Woji Road, Port Harcourt", zone: "Eastern" },
  { name: "Tobis Clinic & Consultants", address: "Yenagoa, Bayelsa State", zone: "Eastern" },
  { name: "Valentine Hospital", address: "Old GRA, Port Harcourt", zone: "Eastern" },
  { name: "Westhill Hospital", address: "Omoku Street, Port Harcourt", zone: "Eastern" },
  { name: "Woji Cottage Hospital", address: "ALCON Road, Port Harcourt", zone: "Eastern" },

  // Central Zonal Register
  { name: "BU Clinic/Hospital Ltd", address: "Ugborikoko, Warri, Delta", zone: "Central" },
  { name: "Bendel Clinic", address: "Effurun, Delta State", zone: "Central" },
  { name: "Bryant Hospital", address: "Off Emebiren Street, Warri", zone: "Central" },
  { name: "Capitol Hill Clinic", address: "Deco Road, Warri", zone: "Central" },
  { name: "Carin Heights Specialist Hospital", address: "Sapele, Delta State", zone: "Central" },
  { name: "Day Spring Clinic", address: "Bendel Estate, Warri", zone: "Central" },
  { name: "Delta Procare Clinic/Hospital", address: "DSC Expressway, Effurun", zone: "Central" },
  { name: "Fairview Hospital", address: "Okumagba Avenue, Warri", zone: "Central" },
  { name: "Lily Hospital Limited", address: "Deco Road, Warri", zone: "Central" },
  { name: "Pal Clinics And Maternity", address: "Ogunu Road, Warri", zone: "Central" },
  { name: "Ragal Clinic", address: "222, Jakpa Road, Effurun", zone: "Central" },
  { name: "St. George's Specialist Clinic", address: "Effurun, Warri", zone: "Central" },
  { name: "Twins Clinic", address: "Twins Clinic Drive, Warri", zone: "Central" },
  { name: "Unity Clinic", address: "Warri-Sapele Road, Warri", zone: "Central" },
  { name: "Vertimon Medical Clinics Ltd.", address: "3, Merogun Road, Warri", zone: "Central" },
  { name: "Westend Hospital And Diagnostic Centre", address: "Airport Road, Warri", zone: "Central" },

  // Northern Zonal Register
  { name: "King's Care Hospital Limited", address: "Wuse Zone 4, Abuja", zone: "Northern" },
  { name: "Sauki Private Hospital", address: "5, Juba Street, Zone 6, Wuse, Abuja", zone: "Northern" },
];
